---
database:
  driver: mysql
  username: ssh_management
  password: password
  database: ssh_management
  host: mysql:3306
  collation: utf8mb4_unicode_ci
  conn_max_idle_time: 30s
  conn_max_lifetime: 5m
  conn_max_idle: 10
  conn_max_opened: 10

bind: '0.0.0.0'
port: 8080

logging:
  file: /var/log/ssh_management/server.log
  level: info
  console: true
  sample: 0

system_groups:
  sudo: sudo

crypto:
  ed25519:
    public: './keys/public.key'
    private: './keys/private.key'
  auth_key: ''
  enc_key: ''

views:
  static:
    dir: ./static
    path: /static

redis:
  host: redis
  port: 6379
  username: ''
  password: ''

queue:
  concurrency: 10
  logging:
    file: /var/log/ssh_management/queue.log
    level: info
    console: true
