---
database:
  driver: mysql
  username: server
  password: server
  database: ssh_management
  host: mysql:3306
  collation: utf8mb4_unicode_ci
  conn_max_idle_time: 30s
  conn_max_lifetime: 5m
  conn_max_idle: 10
  conn_max_opened: 10

http:
  bind: '0.0.0.0'
  port: 8080
  domain: localhost

logging:
  file: /var/log/ssh_management/server.log
  level: info
  console: true
  sample: 0

system_groups:
  sudo: sudo

crypto:
  ed25519:
    public: './keys/public.key'
    private: './keys/private.key'
  auth_key: ''
  enc_key: ''
  password:
    driver: bcrypt
    bcrypt:
      cost: 10

views:
  static:
    dir: ./static
    path: /static

redis:
  host: redis
  port: 6379
  username: ''
  password: ''
  session:
    db: 1
  csrf:
    db: 2
  queue:
    db: 3

session:
  expiration: 1h
  lookup: ssh_management_id
  cookie_path: /
  secure: false
  same_site: Lax

csrf:
  expiration: 1h
  lookup: ssh_management_csrf
  cookie_path: /
  secure: false
  same_site: Lax

cors:
  headers:
    - Content-Type
    - Accept
  origins:
    - localhost:8080
    - locahost:3000
  methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS

queue:
  concurrency: 10
  logging:
    file: /var/log/ssh_management/queue.log
    level: info
    console: true
