---
#------------------------------------------------------------------------------
# Database
#------------------------------------------------------------------------------
database:
  driver: mysql
  username: ssh_management
  password: password
  database: ssh_management
  host: mariadb:3306
  collation: utf8mb4_unicode_ci
  conn_max_idle_time: 30s
  conn_max_lifetime: 5m
  conn_max_idle: 10
  conn_max_opened: 10

bind: '0.0.0.0'
port: 8080

logging:
  file: /var/logs/ssh_management/server.log
  level: info
  console: true
  sample: 0

crypto:
  ed25519:
    public: './keys/public.key'
    private: './keys/private.key'
  #------------------------------------------------------------------------------
  # Authentication key used for HMAC token signing and secure cookies
  #------------------------------------------------------------------------------
  auth_key: ''

  #------------------------------------------------------------------------------
  # Encryption key used for encrypting cookies
  #------------------------------------------------------------------------------
  enc_key: ''

views:
  #------------------------------------------------------------------------------
  # Templates directory
  #------------------------------------------------------------------------------
  static:
    dir: ./static
    path: /static

#------------------------------------------------------------------------------
# Redis server (used for rate limiting)
#------------------------------------------------------------------------------
redis:
  host: localhost
  port: 6379
  username: ''
  password: ''
